[project]
name = "todo-fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "ruff>=0.14.0",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.37.0",
]
